#!/usr/bin/env bash
set -e

greentext() {
    printf "\x1B[32m%b\e[0m\n" "$1"
}

if [ -f "./.lock" ]; then
	source .lock
	if [[ ! -z $1 ]]; then
		# This will run the user's command
		eval "docker-compose $DOCKER_ARGS exec -T bch-node bitcoin-cli -conf=/bitcoin.conf $@"
	else
		# If the user gave no arguments, we'll just generate a block
		printf "Generating 1 block ... "
		eval "docker-compose $DOCKER_ARGS exec bitcoind-regtest bitcoin-cli -conf=/bitcoin.conf generate 1"
		greentext "done"
	fi
else
	printf "Use this script AFTER you've run ./setup and ./services start\n"
	exit 0
fi
