#!/usr/bin/env bash
set -u

DID_SOMETHING=0

deleteIfExists() {
    if [[ -f "$2" || -d "$2" ]]; then
        printf "Removing $1 ... "
        rm -rf $2
        greentext "done"
        DID_SOMETHING=1
    fi
}

greentext() {
    printf "\x1B[32m%b\e[0m\n" "$1"
}

if [[ -f "./.lock" ]]; then
	source .lock
	eval "docker-compose $DOCKER_ARGS down"
	DID_SOMETHING=1
fi

# Remove node data files
deleteIfExists "noda data" "./data/bitcoind"

# Remove SLPDB data files
deleteIfExists "SLPDB data" "./data/mongodb"

# Remove indexer data files
deleteIfExists "indexer data" "./data/fulcrum"

# Remove config file and lock
deleteIfExists "config file" "./config.json"
deleteIfExists "lock" "./.lock"

deleteIfExists "openssl certificate" "./configs/cert"

if [[ $DID_SOMETHING == 1 ]]; then
    printf "Finished\n"
else
    printf "Nothing to do.\n"
fi
