#!/usr/bin/env bash

DID_SOMETHING=0

if [ -d "./cert" ]; then
	echo "Removing certificates directory."
	rm -rf cert
	DID_SOMETHING=1
fi

if [ -d "./Electron-Cash-SLP" ]; then
	echo "Removing Electron-Cash-SLP directory."
	rm -rf Electron-Cash-SLP
	DID_SOMETHING=1
fi

BTK_ENV=`uname`
if [[ $BTK_ENV == "Darwin" ]];then
	ECW_DIR="/Users/`whoami`/.electron-cash"
fi

if [[ $BTK_ENV == "Linux" || $BTK_ENV == "FreeBSD" ]];then
	ECW_DIR="/home/`whoami`/.electron-cash"
fi

if [ -d "$ECW_DIR" ]; then
	
	while true; do
		echo "This script is going to DELETE your electron-wallet directory in your home folder." 
		read -p "Continue? [Y/n] " yn
		case $yn in
			[Yy]* ) echo "Removing Electron-Cash wallet directory in home folder" && rm -rf $ECW_DIR && DID_SOMETHING=1 && break;;
			[Nn]* ) echo "Okay." && break;;
			* ) echo "Please answer yes or no.";;
		esac
	done
fi

if [ -f "./docker_container_ids.txt" ]; then
	echo "Removing previous docker containers"
	CONTAINER_IDS=`cat ./docker_container_ids.txt`
	docker stop $CONTAINER_IDS
	docker rm $CONTAINER_IDS
	rm ./docker_container_ids.txt
fi

if [ $DID_SOMETHING -eq 1 ]; then
	echo "Done."
else
	echo "Nothing to do."
fi
