version: "3"
services:
    bitcoind-regtest:
        image: zquestz/bitcoin-unlimited
        container_name: bitcoind-regtest
        ports:
          - "18443:18443"
          - "28332:28332"
          - "50001:50001"
        volumes:
          - ./data/bitcoind:/data
          - ./configs/bitcoin-unlimited.conf:/data/bitcoin.conf
          - ./configs/bitcoin-unlimited.conf:/root/.bitcoin/bitcoin.conf
            #entrypoint: "/entrypoint.sh"
        command: bitcoind
        networks:
          - bitcoin-bridging

    # bitcoind-regtest:
    #     image: zquestz/bitcoin-cash-node
    #     container_name: bitcoind-regtest
    #     ports:
    #       - "18443:18443"
    #       - "28332:28332"
    #     volumes:
    #       - ./data/bitcoind:/data
    #       - ./configs/bitcoin.conf:/data/bitcoin.conf
    #       - ./configs/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    #     entrypoint: "/entrypoint.sh"
    #     command: bitcoind
    #     networks:
    #       - bitcoin-bridging

    # fulcrum:
    #     image: cculianu/fulcrum
    #     container_name: fulcrum
    #     depends_on:
    #      - bitcoind-regtest
    #     ports:
    #       - "50001:50001"
    #     volumes:
    #       - ./data/fulcrum:/data
    #       - ./configs/fulcrum-config.conf:/config.conf
    #     command: ["Fulcrum", "/config.conf"]
    #     networks:
    #       - bitcoin-bridging

    nginx-regtest:
        image: nginx:latest
        container_name: nginx-regtest
        ports:
         - "50002:50002"
        volumes:
         - ./configs/nginx.conf:/etc/nginx/nginx.conf
         - ./configs/cert/cert.key:/etc/nginx/cert.key
         - ./configs/cert/cert.crt:/etc/nginx/cert.crt
        networks:
         - bitcoin-bridging

    opensight:
        image: actorforth/opensight:latest
        container_name: opensight
        ports:
          - "3001:3001"
        environment:
          - ELECTRUM_HOST=bitcoind-regtest
          - ELECTRUM_PORT=50001
          - NODE_RPC_PORT=18443
        networks:
          - bitcoin-bridging

    bitcoin-restapi:
        image: rest5:latest
        container_name: bitcoin-restapi
        ports:
          - "12500:3000"
        environment: 
          - BITCOINCOM_BASEURL=http://opensight:3001/api/
          - RPC_BASEURL=http://bitcoind-regtest:18443/
          - RPC_PASSWORD=regtest
          - RPC_USERNAME=regtest
          - ZEROMQ_URL=0
          - ZEROMQ_PORT=0
          - NETWORK=regtest
        volumes:
          - ./configs/restapi-config.sh:/home/node/app/start.sh
        networks:
          - bitcoin-bridging

    bch-api-regtest:
        image: actorforth/bch-api:latest-dev
        container_name: bch-api-regtest
        command: "node ./src/app.js"
        ports:
          - "3000:3000"
          # volumes:
          #   - ./:/home/safeuser/bch-api/
        restart: always
        environment:
          - RPC_BASEURL=http://bitcoind-regtest:18443/
          - RPC_USERNAME=regtest
          - RPC_PASSWORD=regtest
          - NETWORK=regtest
          - SLPDB_URL=http://slpserve:4000/
          # - BLOCKBOOK_URL=https://<Blockbook IP>:9131/
          - NODE_TLS_REJECT_UNAUTHORIZED=0
          - FULCRUM_URL=nginx-regtest
          - FULCRUM_PORT=50002
          - SECURITY=false
          - TOKENSECRET=somelongpassword
          - DO_NOT_USE_RATE_LIMITS=true
          # - REDIS_HOST=6379
          # - REDIS_PORT=127.0.0.1
        networks:
          - bitcoin-bridging

    mongodb:
        image: mongo:4.2-bionic
        container_name: mongo-slpdb
        ports:
          - "27017:27017"
        volumes:
          - ./data/mongodb:/data/db
        command: mongod
        networks:
          - bitcoin-bridging

    slpdb:
        image: actorforth/slpdb:latest-dev
        container_name: slpdb
        links:
          - mongodb
        volumes:
          - ./configs/slpdb-config.sh:/home/safeuser/start.sh
        restart: always
        depends_on:
          - mongodb
        networks:
          - bitcoin-bridging

    slpserve:
        image: actorforth/slpserve:latest
        container_name: slpserve
        volumes:
            #          - ./configs/slpserve:/home/safeuser/config
          - ./configs/slpserve-config.sh:/home/safeuser/slpserve/start.sh
        links:
          - mongodb
        ports:
          - "12300:4000"
        restart: always
        depends_on:
          - mongodb
        networks:
          - bitcoin-bridging

networks:
  bitcoin-bridging:
    external: true
