version: "3"
networks:
  bch-devsuite-network:
    external: true
services:
  ##############
  # LOCAL NODE #
  ##############
  # Bitcoin Unlimited Node
  bch-node:
    image: ghcr.io/actorforth/bitcoin-unlimited:${TAG_BITCOINUNLIMITED:-latest}
    container_name: bch-node
    volumes:
      - ./data/bitcoind:/data
      - ./configs/bitcoin-unlimited.conf:/bitcoin.conf
    restart: always
    command: ["bitcoind", "-conf=/bitcoin.conf"]
    networks:
      - bch-devsuite-network
    ports:
      - "18443:18443"
      - "28332:28332"
      - "50001:50001"

  ################
  # REST SERVICE #
  ################
  # bchrest
  bchrest:
    image: ghcr.io/actorforth/bchrest:${TAG_BCHREST:-latest}
    container_name: bchrest
    environment:
      - BITCOINCOM_BASEURL=http://opensight:3001/api/
      - DO_NOT_USE_RATE_LIMITS=true
      - NETWORK=regtest
      - PORT=3000
      - RPC_BASEURL=http://bch-node:18443/
      - RPC_PASSWORD=1234
      - RPC_USERNAME=test
      - SLPDB_URL=http://slpserve:4000/
      - ZEROMQ_PORT=0
      - ZEROMQ_URL=0
    restart: always
    command: ["npm", "start"]
    networks:
      - bch-devsuite-network
    ports:
      - "12500:3000"
  opensight:
    image: ghcr.io/actorforth/opensight:${TAG_OPENSIGHT:-latest}
    container_name: opensight
    environment:
      - ELECTRUM_HOST=bch-node
      - ELECTRUM_PORT=50001
      - NODE_RPC_HOST=bch-node
      - NODE_RPC_PASS=1234
      - NODE_RPC_PORT=18443
      - NODE_RPC_USER=test
      - OPENSIGHT_PORT=3001
    restart: always
    networks:
      - bch-devsuite-network
    ports:
      - "3001:3001"
  #######
  # SLP #
  #######
  mongodb-slpdb:
    image: mongo:${TAG_MONGODB:-latest}
    container_name: mongodb-slpdb
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: always
    command: mongod
    networks:
      - bch-devsuite-network
    ports:
      - "27017:27017"
  slpdb:
    image: ghcr.io/actorforth/slpdb:${TAG_SLPDB:-latest}
    container_name: slpdb
    depends_on:
      - mongodb-slpdb
    volumes:
      - ./configs/slpdb-config.sh:/home/safeuser/start.sh
    environment:
      - db_url=mongodb://test:1234@mongodb-slpdb:27017?connectTimeoutMS=90000&socketTimeoutMS=90000
      - rpc_host=bch-node
      - rpc_pass=1234
      - rpc_port=18443
      - rpc_user=test
      - zmq_incoming_host=bch-node
    restart: always
    networks:
      - bch-devsuite-network
  slpserve:
    image: ghcr.io/actorforth/slpserve:${TAG_SLPSERVE:-latest}
    container_name: slpserve
    depends_on:
      - mongodb-slpdb
    environment:
      - db_name=slpdb_test
      - db_url=mongodb://test:1234@mongodb-slpdb:27017
      - slpserve_log=true
      - slpserve_port=4000
      - slpserve_timeout=30000
    restart: always
    command: ["npm", "start"]
    networks:
      - bch-devsuite-network
    ports:
      - "12300:4000"
