FROM alpine:20200626

RUN addgroup -S bitcoin && useradd -S -h /home/bitcoin -G bitcoin bitcoin

RUN set -ex \
	&& apk update \
	&& apk add ca-certificates gnupg gosu wget \
	# ^ This is incomplete. More deps are needed to run BU

ENV BITCOIN_VERSION 1.8.0.0
ENV BITCOIN_URL https://www.bitcoinunlimited.info/downloads/bch-unlimited-1.8.0.0-linux64.tar.gz
ENV BITCOIN_SHA256 d36da1380e2b5c5412c52be958a7583bcab6d7a7bbb8057417eb892851e8bdd4

# install bitcoin binaries
RUN set -ex \
	&& cd /tmp \
	&& wget -qO bitcoin.tar.gz "$BITCOIN_URL" \
	&& echo "$BITCOIN_SHA256 bitcoin.tar.gz" | sha256sum -c - \
	&& tar x -zvf bitcoin.tar.gz --exclude=*-qt \
	&& cp bch-unlimited-1.8.0.0/* /usr/local/
	&& rm -rf /tmp/*

# create data directory
ENV BITCOIN_DATA /data
RUN mkdir "$BITCOIN_DATA" \
	&& chown -R bitcoin:bitcoin "$BITCOIN_DATA" \
	&& ln -sfn "$BITCOIN_DATA" /home/bitcoin/.bitcoin \
	&& chown -h bitcoin:bitcoin /home/bitcoin/.bitcoin
VOLUME /data

COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 8332 8333 18332 18333
CMD ["bitcoind"]
