version: "3"
services:
    bitcoind-regtest:
        image: zquestz/bitcoin-unlimited
        container_name: bitcoind-regtest
        expose:
          - "18332"
          - "18444"
          - "28332"
          - "50001"
        ports:
          - "18332:18332"
          - "18444:18444"
          - "28332:28332"
          - "50001:50001"
        volumes: 
          - ./bitcoin.conf:/data/bitcoin.conf
        entrypoint: "/entrypoint.sh" 
        command: bitcoind 

    nginx-regtest:
        image: nginx:latest
        container_name: nginx-regtest 
        expose:
          - "50002"
        ports:
          - "50002:50002"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./cert/cert.key:/etc/nginx/cert.key
          - ./cert/cert.crt:/etc/nginx/cert.crt
            #        depends_on:
            #          - bitcoind-regtest

