#!/usr/bin/env bash

if [ -f "./docker_container_ids.txt" ]; then
	echo "Generating some blocks..."
	DK_BU=`cat ./docker_container_ids.txt | awk '{ print $1 }'`
	docker exec -u bitcoin -i $DK_BU bitcoin-cli generate 10
	echo "Blocks generated."
	echo "Please go check in 'Networks' that localhost is not banned."
else
	echo "Use this fix script AFTER ./setup and ./run"
	echo "Please note, the wallet should be actively running when you use this script."
fi
