#!/usr/bin/env bash

if [[ ! -d "./Electron-Cash-SLP" && ! -d "./Electron-Cash-SLP/venv" ]]; then
	echo "Please execute the 'setup' script first."
	exit 1
else
	# Check that we have docker-compose installed
	if [ ! -x "$(command -v docker-compose)" ]; then
		echo "Docker-compose not found. Please install docker-compose."
		exit 1
	fi

	echo "Running nodes and Electron Cash SLP wallet"

	docker-compose -d up

	sleep 4 

	cd ./Electron-Cash-SLP
	source ./venv/bin/activate
	./electron-cash -testnet -v

fi
