#!/usr/bin/env bash
set -e

BTK_SERVICES_RUN=0
BTK_SERVICES_STOP=0
BTK_RUN_WALLET=0

BTK_SLEEP_TIME=6

if [[ ! -f "./.env" ]]; then
	echo "Please execute the 'setup' script first."
	exit 1
else

	if [[ ! -z $1 ]]; then
		for var in "$@"
		do
			[[ $var == "run" || $var == "start" ]] && BTK_SERVICES_RUN=1
            [[ $var == "stop" ]] && BTK_SERVICES_STOP=1
			[[ $var == "run-wallet" ]] && BTK_RUN_WALLET=1
		done
			else
		echo "usage: run [command]"
		echo " - start: start the services specific during setup (i.e. node, rest, slpdb)"
        echo " - stop: stops the services that are currently running"
		echo " - run-wallet: start the Electron Cash SLP wallet"

		exit 0
	fi
fi

# Check that we have docker-compose installed
if [ ! -x "$(command -v docker-compose)" ]; then
	echo "Docker-compose not found. Please install docker-compose."
	exit 1
fi

# Ensure only one of two exclusive commands are chosen
if [[ $BTK_SERVICES_RUN == 1 && $BTK_SERVICES_STOP == 1 ]]; then
    echo "You can't start and stop services at the same time..."
    exit 1
fi

if [[ $BTK_RUN_WALLET == 1 ]]; then
		
	echo "Running nodes and Electron Cash SLP wallet"

	docker-compose up -d

	sleep 6

	cd ./Electron-Cash-SLP
	source ./venv/bin/activate
	./electron-cash --testnet -v
	
	docker-compose stop
fi

if [[ $BTK_SERVICES_RUN == 1 ]]; then
	docker-compose up -d
fi

if [[ $BTK_SERVICES_STOP == 1 ]]; then
    docker-compose exec -T bitcoind-regtest bitcoin-cli stop
    sleep $BTK_SLEEP_TIME
    docker-compose stop
fi
