version: "3"
services:
    bch-api:
        image: actorforth/bch-api:${TAG_BCHAPI:-latest}
        container_name: bch-api
        ports:
          - "3000:3000"
        environment:
          - RPC_BASEURL=http://bch-node:18443/
          - RPC_USERNAME=regtest
          - RPC_PASSWORD=regtest
          - NETWORK=regtest
          - SLPDB_URL=http://slpserve:4000/
          # - BLOCKBOOK_URL=https://<Blockbook IP>:9131/
          - NODE_TLS_REJECT_UNAUTHORIZED=0
          - FULCRUM_URL=bch-nginx
          - FULCRUM_PORT=50002
          - SECURITY=false
          - TOKENSECRET=somelongpassword
          # - REDIS_HOST=6379
          # - REDIS_PORT=127.0.0.1
        restart: always
        command: ["node", "./src/app.js"]
        networks:
          - ${BTK_DOCKER_NETWORK:-bch-toolkit-network}
