version: "3"
services:
    bch-api:
        image: actorforth/bch-api:${TAG_BCHAPI:-latest}
        container_name: bch-api
        environment:
          - RPC_BASEURL=${RPC_BASEURL}
          - RPC_USERNAME=${RPC_USERNAME} # this needs to be grabbed from pass config file and exported
          - RPC_PASSWORD=${RPC_PASSWORD}
          - NETWORK=${NETWORK}
          - SLPDB_URL=http://slpserve:4000/
          - BLOCKBOOK_URL=https://<Blockbook IP>:9131/
          - NODE_TLS_REJECT_UNAUTHORIZED=0
          - FULCRUM_URL=bch-nginx
          - FULCRUM_PORT=50002
          - SECURITY=false
          - TOKENSECRET=somelongpassword
          - REDIS_HOST=6379
          - REDIS_PORT=127.0.0.1
        restart: always
        command: ["node", "./src/app.js"]
        networks:
          - ${BTK_DOCKER_NETWORK:-bch-toolkit-network}
