version: "3"
services:
    bch-api-regtest:
        image: actorforth/bch-api:${TAG_BCHAPI:-latest}
        container_name: bch-api
        ports:
          - "3000:3000"
          # volumes:
          #   - ./:/home/safeuser/bch-api/
        restart: always
        environment:
          - RPC_BASEURL=http://bitcoind-regtest:18443/
          - RPC_USERNAME=regtest
          - RPC_PASSWORD=regtest
          - NETWORK=regtest
          - SLPDB_URL=http://slpserve:4000/
          # - BLOCKBOOK_URL=https://<Blockbook IP>:9131/
          - NODE_TLS_REJECT_UNAUTHORIZED=0
          - FULCRUM_URL=nginx-regtest
          - FULCRUM_PORT=50002
          - SECURITY=false
          - TOKENSECRET=somelongpassword
          # - REDIS_HOST=6379
          # - REDIS_PORT=127.0.0.1
        command: ["node", "./src/app.js"]
        networks:
          - bch-toolkit-network

networks:
  bch-toolkit-network:
    external: true
