version: "3"
services:
    bchrest:
        image: actorforth/bchrest:${TAG_BCHREST:-latest-dev}
        container_name: bchrest
        ports:
          - "12500:3000"
        environment:
          - PORT=3000
          - BITCOINCOM_BASEURL=http://opensight:3001/api/
          - RPC_BASEURL=http://bch-node:18443/
          - RPC_PASSWORD=regtest
          - RPC_USERNAME=regtest
          - ZEROMQ_URL=0
          - ZEROMQ_PORT=0
          - NETWORK=regtest
          - DO_NOT_USE_RATE_LIMITS=true
        restart: always
        command: ["npm", "start"]
        networks:
          - ${BTK_DOCKER_NETWORK:-bch-toolkit-network}
