version: "3"
services:
    bchrest:
        image: actorforth/bchrest:${TAG_BCHREST:-latest}
        container_name: bchrest
        ports:
          - "12500:3000"
        restart: always
        environment:
          - PORT=3000
          - BITCOINCOM_BASEURL=http://opensight:3001/api/
          - RPC_BASEURL=http://bch-node:18443/
          - RPC_PASSWORD=regtest
          - RPC_USERNAME=regtest
          - ZEROMQ_URL=0
          - ZEROMQ_PORT=0
          - NETWORK=regtest
        command: ["npm", "start"]
        networks:
          - bch-toolkit-network

networks:
  bch-toolkit-network:
    external: true
