version: "3"
services:
    mongodb-slpdb:
        image: mongo:${TAG_MONGODB:-latest}
        container_name: mongodb-slpdb
        ports:
          - "27017:27017"
        volumes:
          - ../data/mongodb:/data/db
        command: mongod
        networks:
          - bch-toolkit-network

networks:
  bch-toolkit-network:
    external: true
