version: "3"
services:
    slpserve:
        image: actorforth/slpserve:latest
        container_name: slpserve
        volumes:
            #          - ./configs/slpserve:/home/safeuser/config
          - ./configs/slpserve-config.sh:/home/safeuser/slpserve/start.sh
        environment:
          - db_name=slpdb_test
          - db_url=mongodb://mongo-slpdb:27017
          - slpserve_port=4000
          - slpserve_timeout=30000
          - slpserve_log=true
        links:
          - mongodb
        ports:
          - "12300:4000"
        restart: always
        depends_on:
          - mongodb
        command: ["npm", "start"]
        networks:
          - bitcoin-bridging

networks:
  bitcoin-bridging:
    external: true
