version: "3"
services:
  slpdb:
    image: actorforth/slpdb:latest
    container_name: slpdb
    links:
      - mongodb
    volumes:
      - ../configs/slpdb-config.sh:/home/safeuser/SLPDB-src/start.sh
      - ../data/leveldb:/home/safeuser/SLPDB/_leveldb
    depends_on:
      - mongodb
    networks:
      - bitcoin-bridging