version: "3"
services:
  mongodb:
    image: mongo:4.2-bionic
    container_name: mongo-slpdb
    ports:
      - "27017:27017"
    volumes:
      - ../data/mongodb:/data/db
    command: mongod
    networks:
      - bitcoin-bridging