version: "3"
services:
    opensight:
         image: actorforth/opensight:latest
         container_name: opensight
         ports:
           - "3001:3001"
         environment:
           - ELECTRUM_HOST=fulcrum
           - ELECTRUM_PORT=50001
           - NODE_RPC_PORT=18443
         networks:
           - bitcoin-bridging
