version: "3"
services:
  slpserve:
    image: actorforth/slpserve:latest
    container_name: slpserve
    volumes:
      - ../configs/slpserve:/home/safeuser/config
      - ../configs/slpserve-config.sh:/home/safeuser/slpserve/start.sh
    links:
      - mongodb
    ports:
      - "12300:4000"
    depends_on:
      - mongodb
    networks:
      - bitcoin-bridging