name: Run regtest node

on:
  push:
    branches:
      - test-ci

  workflow_dispatch:


jobs:
  run-regtest-node:
    runs-on: ubuntu-latest

    steps:
      
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - name: Clone main repository 
        uses: actions/checkout@v2 
        with: 
          token: ${{ secrets.INFRA_USER_GITHUB_ACTION }} 
          submodules: recursive 
          fetch-depth: 0
      # Clear and resync submodule 
      - name: Clear submodule 
        run:  | 
          git submodule deinit --all -f 
          git submodule update --recursive --init 
      - name: Check if TAG contains dirty 
        run: | 
          TAG=$(git describe --always --tags --dirty --abbrev=7) 
          echo "TAG: $TAG." 
          if [[ "$TAG" == *"dirty" ]]; then 
            echo "The branch is dirty, please check your repo." && exit 1 
          fi
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup
        run: |
          pwd
          ls
          ./setup regtest bu slp bchrest expose-ports
      - name: Start services
        run: ./services start
      - name: sleep
        run: |
          sleep 10
          ls
      - name: Collect Docker Logs
        if: failure()
        uses: jwalton/gh-docker-logs@v2.0.2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.0-alpha.3'
      - name: generate address for create slp token
        run: |
          cd bitcash 
          pip install -r requirements.txt
          python3 create_slp.py



