name: GitHub Actions Demo
on: [push]
jobs:
  run-newman-restbch-regression-test-on-regtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: echo "jame" 
        run: echo 'jame'